# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'WHAL - XSP99477|MICROSOFT|XSP294073|XSP2298619(9ecab35c-73a2-4502-bf74-29cb4df1a04c)'
    subscriptionId: '9ecab35c-73a2-4502-bf74-29cb4df1a04c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'WHALC1-CostAnalyticsApp1'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CostAnalyticsApp.json'
    deploymentMode: 'Incremental'